### ISSUE TITLE
Roadmap basic functionality

### ISSUE THREAD

**Issue by mormahr** [mormahr/barcode.js#1]
## v0.1
- [x] Code39 encoding
  - [x] Basic error checking / soft conversion (lower-case → upper-case, etc.)
- [x] SVG Output

## v0.2
- [x] SVG namespace info, etc.
- [ ] Code39 code quality
- [ ] Image Renderer

## v1.0
- [ ] barcode object instead of string (containing meta data like original text)
- [ ] Renderes with optional text output
  - [ ] SVG
  - [ ] HTML + CSS
  - [ ] Image Renderer?
